version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Install deps
      - n 16
      - yarn install
  build:
    commands:
      - echo Building...
      - yarn workspace @kanaries/graphic-walker build
      - yarn workspace rath-client build2
artifacts:
  files:
    - 'packages/rath-client/build/*'
  name: 'rath/$AWS_REGION-$(date +%Y-%m-%d)'